@REM vendor\bin\phpunit test\SampleTest.php
@REM vendor\bin\phpunit test\Q1Test.php
@REM vendor\bin\phpunit test\Q2Test.php
@REM vendor\bin\phpunit test\Q3Test.php
@REM vendor\bin\phpunit test\Q4Test.php
@REM vendor\bin\phpunit test\Q5Test.php
@REM vendor\bin\phpunit test\Q6Test.php
@REM vendor\bin\phpunit test\Q7Test.php
@REM vendor\bin\phpunit test\Q8Test.php
@REM vendor\bin\phpunit test\Q9Test.php
@REM vendor\bin\phpunit test\Q10Test.php
@REM vendor\bin\phpunit test\Q11Test.php
@REM vendor\bin\phpunit test\Q12Test.php
@REM vendor\bin\phpunit test\Q13Test.php
@REM vendor\bin\phpunit test\Q14Test.php
@REM vendor\bin\phpunit test\Q15Test.php
@REM vendor\bin\phpunit test\Q16Test.php
@REM vendor\bin\phpunit test\Q17Test.php
@REM vendor\bin\phpunit test\Q18Test.php
@REM vendor\bin\phpunit test\Q19Test.php
@REM vendor\bin\phpunit test\Q20Test.php
@REM vendor\bin\phpunit test\Q21Test.php
@REM vendor\bin\phpunit test\Q22Test.php
@REM vendor\bin\phpunit test\Q23Test.php
@REM vendor\bin\phpunit test\Q24Test.php
@REM vendor\bin\phpunit test\Q25Test.php
@REM vendor\bin\phpunit test\Q26Test.php
@REM vendor\bin\phpunit test\Q27Test.php
@REM vendor\bin\phpunit test\Q28Test.php
@REM vendor\bin\phpunit test\Q29Test.php
@REM vendor\bin\phpunit test\Q30Test.php
vendor\bin\phpunit test\Q31Test.php